

{{<layout}}
{{$styles}}
<link href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="/css/vacation_request.css" />
{{/styles}}

{{$content}}

<h1 class="label label-primary">Vacation index</h1>
<br /><br />
<a href="/requests/vacation/create" class="btn btn-small btn-success">Create new Vacation Request</a>

{{/content}}

{{$scripts}}
<script src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
{{/scripts}}
{{/layout}}

