
{{<layout}}
{{$styles}}
<link href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="/css/vacation_request.css" />
{{/styles}}

{{$content}}
<br />
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>New Vacation Request</h3>
    </div>
    <div class="panel-body">
{{vacationRequestForm}}
    </div><!-- panel body -->
</div><!-- panel default -->
{{/content}}


{{$scripts}}
<script src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
<script src="/js/date-pick.js" type="text/javascript"></script>
<script src="/js/requests_vacation.js" type="text/javascript"></script>
{{/scripts}}
{{/layout}}

