{{<layout}}
{{$styles}}
{{/styles}}
{{$content}}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Vacation Details</div>
        <div class="panel-body">

            <div class="row">
                <div class="col-sm-2">
                    <strong>Vacation Type:</strong> 
                </div>
                <div class="col-sm-10">
                    {{vacationType}}
                </div>
            </div><!-- row -->

            <div class="row">
                <div class="col-sm-2">
                    <strong>From:</strong> 
                </div>
                <div class="col-sm-10">
                    {{fromDate}}
                </div>
            </div><!-- row -->

            <div class="row">
                <div class="col-sm-2">
                    <strong>To:</strong> 
                </div>
                <div class="col-sm-10">
                    {{toDate}}
                </div>
            </div><!-- row -->

            <div class="row">
                <div class="col-sm-2">
                    <strong>Submition Date: </strong>
                </div>
                <div class="col-sm-10">
                    {{dateOfSubmission}}
                </div>
            </div><!-- row -->

            <div class="row">
                <div class="col-sm-2">
                    <strong>Status:</strong>
                </div>
                <div class="col-sm-10">
                    {{status}}
                </div>
            </div><!-- row -->

            <div class="row">
                <div class="col-sm-2">
                    <strong> Attachment: </strong>
                </div>
                <div class="col-sm-10">
                    {{attachment}}
                </div>
            </div><!-- row -->
            {{#role}}
            <div class="row">
                <div class="col-sm-2">
                    <strong>Creator:</strong>
                </div>
                <div class="col-sm-10">
                    {{vacationCreator}}
                </div>
            </div><!-- row -->
            {{/role}}




        </div><!-- panel body -->
    </div><!--panel default-->
</div><!--container-->

<br />
<div class="container">
    {{#requestComments}}

    <p>{{user}}  {{body}}  {{created}}</p>
    <br />
    {{/requestComments}}
</div>

<div class="container">
    {{commentForm}}
</div>
{{/content}}
{{$scripts}}
{{/scripts}}
{{/layout}}
