{{<layout}}
{{$styles}}
{{/styles}}
{{$content}}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">Vacation Details</div>
        <div class="panel-body">
            
            <div class="row">
                <div class="col-sm-2">
                    Vacation Type: 
                </div>
                 <div class="col-sm-10">
                    {{vacationType}}
                </div>
            </div><!-- row -->
            
            <div class="row">
                <div class="col-sm-2">
                    From: 
                </div>
                 <div class="col-sm-10">
                    {{fromDate}}
                </div>
            </div><!-- row -->
            
            <div class="row">
                <div class="col-sm-2">
                    To: 
                </div>
                 <div class="col-sm-10">
                    {{toDate}}
                </div>
            </div><!-- row -->
            
            <div class="row">
                <div class="col-sm-2">
                    Submition Date: 
                </div>
                 <div class="col-sm-10">
                    {{dateOfSubmission}}
                </div>
            </div><!-- row -->
            
            <div class="row">
                <div class="col-sm-2">
                    Status: 
                </div>
                 <div class="col-sm-10">
                    {{status}}
                </div>
           </div><!-- row -->
           
            <div class="row">
                <div class="col-sm-2">
                    Attachment: 
                </div>
                 <div class="col-sm-10">
                    {{attachment}}
                </div>
            </div><!-- row -->
            {{#role}}
                <div class="row">
                <div class="col-sm-2">
                    Creator: 
                </div>
                 <div class="col-sm-10">
                    {{vacationCreator}}
                </div>
            </div><!-- row -->
            {{/role}}
            
           
                
            
        </div><!-- panel body -->
    </div><!--panel default-->
</div><!--container-->
{{/content}}
{{$scripts}}
{{/scripts}}
{{/layout}}
