{{<layout}}

{{$styles}}
<link href="/bower_components/fullcalendar/dist/fullcalendar.css" rel="stylesheet" type="text/css"/>
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
<script type='text/javascript' src='/js/fullcalendar-2.3.2/fullcalendar.min.js'></script>
{{/styles}}

{{$content}}
<a href="/settings/holiday/new"><button class="btn btn-small btn-success">Create new Holiday</button></a>
<div id='calendar'></div>
{{/content}}


{{$scripts}}
<script src="/js/moment.js" type="text/javascript"></script>
<script src="/bower_components/fullcalendar/dist/fullcalendar.min.js" type="text/javascript"></script>
<script src="/js/calendar.js" type="text/javascript"></script>
{{/scripts}}

{{/layout}}
