{{<layout}}
{{$content}}
<br><br>
<a href="/settings/holiday/new"><button class="btn btn-small btn-success">Create new Holiday</button></a>
<br><br>
{{filterForm}}
<div class="panel panel-default">

   

      
      <div class="panel-heading">Holidays</div>
      
      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            
            <th>Name</th>
            
            <th>From</th>
            <th>To</th>
            <th colspan="2">Actions</th>
          </tr>
        </thead>
        <tbody>
            {{#holidayList}}
                <tr>
                    <th scope="row">{{id}}</th>
                    <td>{{name}}</td>
                    <td>{{dateFrom}}</td>
                    <td>{{dateTo}}</td>
                    <td>
                       
                       
                        <a href="/settings/holiday/edit/id/{{id}}" data-toggle="tooltip" data-placement="left" title="Edit" >
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                         &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                         <a href="/settings/holiday/delete/id/{{id}}" data-toggle="tooltip" data-placement="left" title="Delete" class="delete_row">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    </td>
                </tr>
                
            {{/holidayList}}  
            
          
          
        </tbody>
      </table>
  


{{/content}}
{{/layout}}
