{{<layout}}
{{$styles}}
<link href="/bower_components/jt.timepicker/lib/bootstrap-datepicker.css" rel="stylesheet" type="text/css"/>
<link href="/bower_components/jt.timepicker/jquery.timepicker.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

{{/styles}}

{{$content}}
 <div class="panel panel-default">
    <div class="panel-heading">
        <h3>Filter Attendance</h3>
    </div>
    <div class="panel-body">
       {{filterForm}}
    </div>
</div>
<div id="accordion">
  {{#list}}
    <h3><span class="badge">{{counter}}</span> {{date}} </h3>
  <div>
      
      <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Date</th>
                        <th>Sign-in Time</th>
                        <th>Sign-out Time</th>
                        <th>#of Hours</th>
                    </tr>
                </thead>
                <tbody>
                    {{#list}}
                        <tr>
                            <td> {{user.name}} </td>
                            <td> {{signInDate}} </td>
                            <td> {{signInTime}} </td>
                            <td> {{signOutTime}} </td>
                            <td> {{hourDifference}} hours</td>
                        </tr>
                    {{/list}}
                </tbody>
            </table>
        </div>
      
      
    <ul>
        
    </ul>
  </div>    
  {{/list}}
</div>

{{/content}}

{{$scripts}}
<script src="/bower_components/jt.timepicker/lib/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="/bower_components/jt.timepicker/jquery.timepicker.min.js" type="text/javascript"></script>
<script src="/js/time.js" type="text/javascript"></script>
<script src="/js/date-pick.js" type="text/javascript"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<script src="/js/accordion.js" type="text/javascript"></script>
{{/scripts}}

{{/layout}}