{{<layout}}
{{$styles}}
<link href="/bower_components/jquery-ui/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css"/>
<link href="/bower_components/jt.timepicker/jquery.timepicker.css" rel="stylesheet" type="text/css"/>
{{/styles}}
{{$content}}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Edit User</h3>
                 <img src="{{photo}}" data-toggle="tooltip" data-placement="left"  class="user-photos" style="height: 70px !important;width: 70px !important;">
    </div>
    <div class="panel-body">
        {{userForm}}
    </div>
</div>
{{/content}}
{{$scripts}}
<script src="/bower_components/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="/bower_components/jt.timepicker/jquery.timepicker.min.js" type="text/javascript"></script>
<script src="/js/time.js" type="text/javascript"></script>
<script src="/js/date-pick.js" type="text/javascript"></script>
{{/scripts}}
{{/layout}}
