{{<layout}}
{{$content}}
<br><br><br><br><br>




<div class="panel panel-default">
      
      <div class="panel-heading">Users</div>

      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Position</th>
            <th>Branch</th>
            <th>Department</th>
            <th>Manager</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            {{#userList}}
                <tr>
                    <th scope="row">{{id}}</th>
                    <td><img src="{{photo}}" class="user-photos" height ='150 px' width='100 px'></td>
                    <td>{{name}}</td>
                    <td>{{position.name}}</td>
                    <td>{{branche.name}}</td>
                    <td>{{department.name}}</td>
                    <td>{{manager.name}}</td>
                    <td>
                        <button class="btn btn-danger">
                            Deactivate
                        </button>
                        <button class="btn btn-default">
                            Edit
                        </button>
                    </td>
                </tr>
                
            {{/userList}}  
            
          
          
        </tbody>
      </table>
    </div>
{{%IMPLICIT-ITERATOR}}
<div class="pagination-bar">
    <ul class="pagination">

        {{#pageNumbers}}
        <li><a href="?page={{.}}">{{.}}</a></li>
        {{/pageNumbers}}

    </ul>
</div>
{{/content}}
{{/layout}}