{{<layout}}
{{$content}}
<br />
<a href="/users/index/new"><button class="btn btn-small btn-success">Create new User</button></a>
<br />
<div class="panel panel-default">
      
      <div class="panel-heading">Users</div>

      <!-- Table -->
      <table class="table">
        <thead>
          <tr>
            <th>ID</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Username</th>
            <th>Position</th>
            <th>Branch</th>
            <th>Department</th>
            <th>Manager</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
            {{#userList}}
                <tr>
                    <th scope="row">{{id}}</th>
                    <td><img src="{{photo}}" class="user-photos" height ='150 px' width='100 px'></td>
                    <td>{{name}}</td>
                    <td>{{username}}</td>
                    <td>{{position.name}}</td>
                    <td>{{branch.name}}</td>
                    <td>{{department.name}}</td>
                    <td>{{manager.name}}</td>
                    <td>
                        <a class="btn btn-danger" href="/users/index/delete/id/{{id}}">Delete</a>
                        <a class="btn btn-default" href="/users/index/edit/id/{{id}}">Edit</a>
                    </td>
                </tr>
                
            {{/userList}}  
            
          
          
        </tbody>
      </table>
    </div>
{{%IMPLICIT-ITERATOR}}
<div class="pagination-bar">
    <ul class="pagination">

        {{#pageNumbers}}
        <li><a href="?page={{.}}">{{.}}</a></li>
        {{/pageNumbers}}

    </ul>
</div>
{{/content}}
{{/layout}}
