{{<layout}}

{{$styles}}
<link href="/bower_components/fullcalendar/dist/fullcalendar.css" rel="stylesheet" type="text/css"/>
<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js'></script>
<script type='text/javascript' src='/js/fullcalendar-2.3.2/fullcalendar.min.js'></script>
{{/styles}}

{{$content}}
<table class="table table-hover">
    <thead>
        <tr>
            <th>Notifications</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Your vacation balance left is 17 Days</td>
        </tr>
        <tr>
            <td>Your vacation request had been accepted</td>
        </tr>
        <tr>
            <td>Your Permission had been rejected</td>
        </tr>
    </tbody>
</table>
{{/content}}


{{$scripts}}
<script src="/js/moment.js" type="text/javascript"></script>
<script src="/bower_components/fullcalendar/dist/fullcalendar.min.js" type="text/javascript"></script>
<script src="/js/calendar.js" type="text/javascript"></script>
{{/scripts}}

{{/layout}}
