{{<layout}}
{{$styles}}
{{/styles}}
{{$content}}
<br />
<div class="panel panel-default">
    <div class="panel-heading"><h3 style="display:inline;"><strong>Permission Details</strong></h3>       
        <a href="/requests/myrequests/index" class="btn btn-info" style="float:right;"> Back To Requests ! </a>
    </div>
    <div class="panel-body">

        <div class="row">
            <div class="col-sm-2">
                <strong> Permission Date: </strong>
            </div>
            <div class="col-sm-10">
                {{permissionDate}}
            </div>
        </div><!-- row -->

        <div class="row">
            <div class="col-sm-2">
                <strong> From: </strong>
            </div>
            <div class="col-sm-10">
                {{fromTime}}
            </div>
        </div><!-- row -->

        <div class="row">
            <div class="col-sm-2">
                <strong>  To: </strong>
            </div>
            <div class="col-sm-10">
                {{toTime}}
            </div>
        </div><!-- row -->

        <div class="row">
            <div class="col-sm-2">
                <strong> Submition Date: </strong>
            </div>
            <div class="col-sm-10">
                {{dateOfSubmission}}
            </div>
        </div><!-- row -->

        <div class="row">
            <div class="col-sm-2">
                <strong> Status: </strong>
            </div>
            <div class="col-sm-10">
                {{status}}
            </div>
        </div><!-- row -->


        {{#role}}
        <div class="row">
            <div class="col-sm-2">
                <strong>  Creator: </strong>       
            </div>
            <div class="col-sm-10">
                {{vacationCreator}}
            </div>
        </div><!-- row -->
        {{/role}}
    </div><!-- panel body -->
</div><!--panel default-->
<br />
<h2><strong>Comments</strong></h2>
<br />
{{#requestComments}}
<h4 style="color:#337ab7;"><strong>{{user}}</strong></h4>
<p> <strong><span style="font-size:18px;">{{body}} </span></strong>
    &nbsp;  <span style="color:rgb(169, 166, 166);"> {{created}}</span>

    {{#iscreator}}
    <a data-toggle="tooltip" data-placement="left" title="Delete" style="float: right;" href="/requests/permission/deletecomment/id/{{id}}"><span class="glyphicon glyphicon-remove"></span></a>
    {{/iscreator}}
</p>


<hr />
{{/requestComments}}
{{commentForm}}
{{/content}}
{{$scripts}}
<script src="/js/showrequestscomment.js" type="text/javascript"></script>
{{/scripts}}
{{/layout}}
