{{<layout}}
{{$styles}}

{{/styles}}

{{$content}}
<div class="panel panel-default">

    <div class="panel-heading">Sick</div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {{#sick}}
                    <tr>
                        <td>{{dateOfSubmission}}</td>
                        <td>{{fromDate}}</td>
                        <td>{{toDate}}</td>
                        <td>{{status}}</td>
                    </tr>
                    {{/sick}}

                </tbody>
            </table>
        </div>
    </div>
</div>

<br>
<div class="panel panel-default">

    <div class="panel-heading">Casual</div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {{#casual}}
                    <tr>
                        <td>{{dateOfSubmission}}</td>
                        <td>{{fromDate}}</td>
                        <td>{{toDate}}</td>
                        <td>{{status}}</td>
                    </tr>
                    {{/casual}}

                </tbody>
            </table>
        </div>
    </div>
</div>

<!--Work from home table-->

<br>
<div class="panel panel-default">

    <div class="panel-heading">Work from home Requests</div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Status</th>

                    </tr>
                </thead>
                 <tbody>
                    {{#annual}}
                    <tr>
                        <td>{{dateOfSubmission}}</td>
                        <td>{{fromDate}}</td>
                        <td>{{toDate}}</td>
                        <td>{{status}}</td>
                    </tr>
                    {{/annual}}

                </tbody>
            </table>
        </div>
    </div>
</div>

{{/content}}

{{$scripts}}

{{/scripts}}

{{/layout}}