{{<layout}}
{{$styles}}
<link href="/bower_components/jt.timepicker/lib/bootstrap-datepicker.css" rel="stylesheet" type="text/css"/>
<link href="/bower_components/jt.timepicker/jquery.timepicker.css" rel="stylesheet" type="text/css"/>
{{/styles}}

{{$content}}



{{/content}}

{{$scripts}}
<script src="/bower_components/jt.timepicker/lib/bootstrap-datepicker.js" type="text/javascript"></script>
<script src="/bower_components/jt.timepicker/jquery.timepicker.min.js" type="text/javascript"></script>

{{/scripts}}

{{/layout}}