{{<layout}}
{{$content}}
<a href="/settings/attendance/new"class="btn btn-small btn-success">Create new Attendance</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">Attendance</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Branch</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#attendances}}
            <tr>
                <td>{{branch}}</td>
                <td>{{startTime}}</td>
                <td>{{endTime}}</td>
                <td>
                <a href="edit/id/{{id}}" data-toggle="tooltip" data-placement="left" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="delete/id/{{id}}" class="delete_row" data-toggle="tooltip" data-placement="left" title="Delete"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
            {{/attendances}}
        </td>
        </tr>
        </tbody>
    </table>
</div>

{{/content}}
{{/layout}}
