base:
  phpSettings:
    display_startup_errors: 1
    display_errors: 1
    html_errors: 1
    date:
      timezone: Africa/Cairo
  bootstrap:
    path: APPLICATION_PATH/Bootstrap.php
    class: Bootstrap
  appnamespace: Application
  autoloaderNamespaces:
    - CamelCaseTech
    - Attendance
  includePaths:
    library: APPLICATION_PATH/../library
  pluginpaths:
    CamelCaseTech_Resource: CamelCaseTech/Resource
  resources:
    modules: true
    frontController:
      moduleDirectory: APPLICATION_PATH/modules
      params:
        displayExceptions: 1
        prefixDefaultModule: 1
      plugins:
          Auth: CamelCaseTech_Resource_Plugin_Auth
          Acl: CamelCaseTech_Resource_Plugin_Acl
    view:
      scriptPath: APPLICATION_PATH/layouts
    entityManager:
      schemaDir: APPLICATION_PATH/../library/Attendance/Entity
      proxyDir: APPLICATION_PATH/data/doctrine/proxies
      proxyNamespace: Proxy
      autoGenerateProxyClasses: 0
    dbal:
      master:
        default: true
        driver: pdo_mysql
        host: localhost
        dbname: attendance
        user: root
        password: ilikerandompasswords

production:
  _extends: base

staging:
  _extends: base

testing:
  _extends: base

development:
  _extends: base

local:
  _extends: base