
{{<layout}}
{{$content}}
<style>
    .content{
        background-color: White;
    }
    .panel{
        margin-bottom: 230px;
    }
    .container {
        width: 1084px;
    }
</style>
<div class="container login-container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Please Sign In</h3>
                </div>
                <div class="panel-body">
                    {{#messages}}
                    <div class="alert alert-danger" role="alert">
                        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                        <span class="sr-only">Error:</span>
                        {{message}}
                    </div>

                    {{/messages}}
                    {{form}}
                </div>
            </div>
        </div>
    </div>
</div>
{{/content}}
{{/layout}}
