{{<layout}}
{{$styles}}

{{/styles}}

{{$content}}
<br>
<div class="panel panel-default">

    <div class="panel-heading">Permissions</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Date Of Submission</th>
                <th>From</th>
                <th>To</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {{!template-with-dereferencing.mustache}}
            {{#permissions}}
            <tr>
                <td><a href="/requests/permission/show/id/{{id}}">{{dateOfSubmission}}</a></td>
                <td>{{fromTime}}</td>
                <td>{{toTime}}</td>
                <td>{{status}}</td>

<!--                <td><a href="delete/id/{{id}}" class="delete_row  btn btn-small btn-primary"> Deactivate</a>
                    &nbsp;<a href="edit/id/{{id}}" class="btn btn-small btn-warning" >Edit</a>
                </td>-->
                <td>
                    {{#cancelActionAllowed}}
                        <a href="cancel/id/{{id}}/requesttype/Permission" class="btn delete_row btn-danger">Cancel</a>
                    {{/cancelActionAllowed}}
                    
                    {{#approveActionAllowed}}
                        <a href="approve/id/{{id}}/requesttype/Permission" class="btn btn-success">Approve</a>
                    {{/approveActionAllowed}}
                    
                    {{#declineActionAllowed}}
                        <a href="decline/id/{{id}}/requesttype/Permission" class="btn btn-danger">Decline</a>
                    {{/declineActionAllowed}}
                </td>
            </tr>
            {{/permissions}}
            </td>
            </tr>
        </tbody>
    </table>
</div>

<!--vacation request--> 

<br>
<div class="panel panel-default">

    <div class="panel-heading">Vacation Requests</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Date Of Submission</th>
                <th>From</th>
                <th>To</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#vacationRequests}}
            <tr>
                <td><a href="/requests/vacation/show/id/{{id}}">{{dateOfSubmission}}</a></td>                <td>{{fromDate}}</td>
                <td>{{toDate}}</td>
                <td>{{status}}</td>

<!--                <td><a href="delete/id/{{id}}" class="delete_row  btn btn-small btn-primary"> Deactivate</a>
                    &nbsp;<a href="edit/id/{{id}}" class="btn btn-small btn-warning" >Edit</a>
                </td>-->
                <td>
                    {{#cancelActionAllowed}}
                        <a href="cancel/id/{{id}}/requesttype/VacationRequest" class="btn delete_row btn-danger">Cancel</a>
                    {{/cancelActionAllowed}}
                    
                    {{#approveActionAllowed}}
                        <a href="approve/id/{{id}}/requesttype/VacationRequest" class="btn btn-success">Approve</a>
                    {{/approveActionAllowed}}
                    
                    {{#declineActionAllowed}}
                        <a href="decline/id/{{id}}/requesttype/VacationRequest" class="btn btn-danger">Decline</a>
                    {{/declineActionAllowed}}
                </td>
            </tr>
            {{/vacationRequests}}
            </td>
            </tr>
        </tbody>
    </table>
</div>

<!--Work from home table-->

<br>
<div class="panel panel-default">

    <div class="panel-heading">Work From Home Requests</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Date Of Submission</th>
                <th>From</th>
                <th>To</th>
                <th>Reason</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#workFromHomeRequests}}
            <tr>
                <td><a href="/requests/workfromhome/show/id/{{id}}">{{dateOfSubmission}}</a></td>
                <td>{{startDate}}</td>
                <td>{{endDate}}</td>
                <td>{{reason}}</td>
                <td>{{status}}</td>

<!--                <td><a href="delete/id/{{id}}" class="delete_row  btn btn-small btn-primary"> Deactivate</a>
                    &nbsp;<a href="edit/id/{{id}}" class="btn btn-small btn-warning" >Edit</a>
                </td>-->
                <td>
                    {{#cancelActionAllowed}}
                        <a href="cancel/id/{{id}}/requesttype/Workfromhome" class="btn delete_row btn-danger">Cancel</a>
                    {{/cancelActionAllowed}}
                    
                    {{#approveActionAllowed}}
                        <a href="approve/id/{{id}}/requesttype/Workfromhome" class="btn btn-success">Approve</a>
                    {{/approveActionAllowed}}
                    
                    {{#declineActionAllowed}}
                        <a href="decline/id/{{id}}/requesttype/Workfromhome" class="btn btn-danger">Decline</a>
                    {{/declineActionAllowed}}
                </td>
            </tr>
            {{/workFromHomeRequests}}
            </td>
            </tr>
        </tbody>
    </table>
</div>

{{/content}}

{{$scripts}}

{{/scripts}}

{{/layout}}