{{<layout}}
{{$styles}}

{{/styles}}

{{$content}}
<div class="panel panel-default">

    <div class="panel-heading">Permissions</div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>Requester</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {{!template-with-dereferencing.mustache}}
                    {{#permissions}}
                    <tr>
                        <td><a href="/requests/permission/show/id/{{id}}">{{dateOfSubmission}}</a></td>
                        <td>{{user.name}}</td>
                        <td>{{fromTime}}</td>
                        <td>{{toTime}}</td>
                        <td>{{status}}</td>

                        <td><a href="delete/id/{{id}}" class="delete_row  btn btn-small btn-primary"> Deactivate</a>
                            &nbsp;<a href="edit/id/{{id}}" class="btn btn-small btn-success" >Edit</a>
                            <!--                </td>
                                            <td>-->
                            {{#approveActionAllowed}}
                            <a href="approve/id/{{id}}/requesttype/Permission" class="btn btn-warning">Approve</a>
                            {{/approveActionAllowed}}

                            {{#declineActionAllowed}}
                            <a href="decline/id/{{id}}/requesttype/Permission" class="btn btn-danger">Decline</a>
                            {{/declineActionAllowed}}

                            {{#cancelActionAllowed}}
                            <a href="cancel/id/{{id}}/requesttype/Permission" class="btn delete_row btn-info">Cancel</a>
                            {{/cancelActionAllowed}}


                        </td>
                    </tr>
                    {{/permissions}}
                    </td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

<br>
<div class="panel panel-default">

    <div class="panel-heading">Vacation Requests</div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>Requester</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {{#vacationRequests}}
                    <tr>
                        <td><a href="/requests/vacation/show/id/{{id}}">{{dateOfSubmission}}</a></td>                
                        <td>{{user.name}}</td>
                        <td>{{fromDate}}</td>
                        <td>{{toDate}}</td>
                        <td>{{status}}</td>

                        <td>
                            {{#approveActionAllowed}}
                            <a href="approve/id/{{id}}/requesttype/VacationRequest" class="btn btn-primary">Approve</a>
                            {{/approveActionAllowed}}

                            {{#declineActionAllowed}}
                            <a href="decline/id/{{id}}/requesttype/VacationRequest" class="btn btn-success">Decline</a>
                            {{/declineActionAllowed}}

                            {{#cancelActionAllowed}}
                            <a href="cancel/id/{{id}}/requesttype/VacationRequest" class="btn delete_row btn-danger">Cancel</a>
                            {{/cancelActionAllowed}}


                        </td>
                    </tr>
                    {{/vacationRequests}}
                    </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--Work from home table-->

<br>
<div class="panel panel-default">

    <div class="panel-heading">Work from home Requests</div>

    <div class="panel-body">
        <div class="dataTable_wrapper">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Date Of Submission</th>
                        <th>Requester</th>
                        <th>From</th>
                        <th>To</th>
                        <th>Reason</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {{#workFromHomeRequests}}
                    <tr>
                        <td><a href="/requests/workfromhome/show/id/{{id}}">{{dateOfSubmission}}</a></td>
                        <td>{{user.name}}</td>
                        <td>{{startDate}}</td>
                        <td>{{endDate}}</td>
                        <td>{{reason}}</td>
                        <td>{{status}}</td>

<!--                <td><a href="delete/id/{{id}}" class="delete_row  btn btn-small btn-primary"> Deactivate</a>
                    &nbsp;<a href="edit/id/{{id}}" class="btn btn-small btn-warning" >Edit</a>
                </td>-->
                        <td>

                            {{#approveActionAllowed}}
                            <a href="approve/id/{{id}}/requesttype/Workfromhome" class="btn btn-primary">Approve</a>
                            {{/approveActionAllowed}}

                            {{#declineActionAllowed}}
                            <a href="decline/id/{{id}}/requesttype/Workfromhome" class="btn btn-success">Decline</a>
                            {{/declineActionAllowed}}

                            {{#cancelActionAllowed}}
                            <a href="cancel/id/{{id}}/requesttype/Workfromhome" class="btn delete_row btn-danger">Cancel</a>
                            {{/cancelActionAllowed}}

                        </td>
                    </tr>
                    {{/workFromHomeRequests}}
                    </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{{/content}}

{{$scripts}}

{{/scripts}}

{{/layout}}