{{<layout}}
{{$content}}
<br><br>
<a href="/settings/attendance/new"class="btn btn-small btn-success">Create new Attendance</a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">Attendance</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Branch</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#attendances}}
            <tr>
                <td>{{branch}}</td>
                <td>{{startTime}}</td>
                <td>{{endTime}}</td>
                <td><a href="delete/id/{{id}}" class="btn btn-small btn-primary delete_row">Deactivate</a>
                    &nbsp;<a href="edit/id/{{id}}" class="btn btn-small btn-warning ">Edit</a>
            </tr>
            {{/attendances}}
        </td>
        </tr>
        </tbody>
    </table>
</div>

{{/content}}
{{/layout}}
