{{<layout}}
{{$content}}
<br><br>
<a href="/settings/attendance/new"><button class="btn btn-small btn-success">Create new Attendance</button></a>
<br><br>
<div class="panel panel-default">

    <div class="panel-heading">Vacations</div>

    <!-- Table -->
    <table class="table">
        <thead>
            <tr>
                <th>Branch</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {{#attendances}}
            <tr>
                <td>{{branch}}</td>
                <td>{{startDate}}</td>
                <td>{{endDate}}</td>
                <td><a href="delete/id/{{id}}"><button class="btn btn-small btn-primary">Deactivate</button></a>
                    &nbsp;<a href="edit/id/{{id}}"><button class="btn btn-small btn-warning">Edit</button></a>
            </tr>
            {{/attendances}}
        </td>
        </tr>
        </tbody>
    </table>
</div>

{{/content}}
{{/layout}}
