{{<layout}}
    {{$styles}}
        <link href="/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css"/>
    {{/styles}}

    {{$content}}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>Edit Holiday</h3>
            </div>
            <div class="panel-body">
                {{editForm}}
            </div>
        </div>
    {{/content}}

    {{$scripts}}
        <script src="/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js" type="text/javascript"></script>
        <script src="/js/date-pick.js" type="text/javascript"></script>
    {{/scripts}}
{{/layout}}
