{{<layout}}
    {{$styles}}   
            <link href="/bower_components/jquery-ui/themes/smoothness/jquery-ui.min.css" rel="stylesheet" type="text/css"/>
    {{/styles}}

    {{$content}}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>New Holiday</h3>
            </div>
            <div class="panel-body">
                {{form}}
            </div>
        </div>
    {{/content}}

    {{$scripts}}
        <script src="/bower_components/jquery-ui/ui/minified/jquery-ui.min.js" type="text/javascript"></script>
        <script src="/js/date-pick.js" type="text/javascript"></script>
    {{/scripts}}
{{/layout}}
