<!doctype html>
<html>

    <head>
        <title>Attendance System</title>
        <meta charset="UTF-8">

        <link rel="stylesheet" href="/css/template-styling.css" />
        <link href="/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="/bower_components/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet" type="text/css"/>
        <link href="/bower_components/startbootstrap-sb-admin-2/dist/css/timeline.css" rel="stylesheet" type="text/css"/>
        <!-- Additional styles to be added to specific views -->
        {{$styles}}{{/styles}}

    </head>

    <body>
        <nav class="navbar navbar-default navbar-static-top" role="navigation" >
            <div class="navbar-header">
                <a class="navbar-brand" href="index.html">Attendance HUB</a>
            </div>
        </nav>

        <div class="myrow row">
            <div class="col-xs-2 col-md-2">
                <ul class="nav in" id="side-menu">
                    <li>
                        <h3><i class="fa fa-dashboard fa-fw"></i> Dashboard</h3>
                    </li>
                    <!--Users Module-->
                    <li>
                        <a href="/users"><i class="fa fa-bar-chart-o fa-fw"></i>Users Module &nbsp;&nbsp;<span class="fa arrow glyphicon glyphicon-user"></span></a>
                    </li>
                    <!--Users Module-->   
                    <!--Settings Module-->
                    <li>
                        <a href="#" ><i class="fa fa-sitemap fa-fw " ></i>Settings Module&nbsp;&nbsp;<span class="fa arrow glyphicon glyphicon-wrench"></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                                <a href="/settings/vacation/index">Vacation</a>
                            </li>
                            <li>
                                <a href="/settings/holiday/index">Holidays</a>
                            </li>
                            <li>
                                <a href="/settings/attendance/index">Attendance</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <!--Settings Module-->

                    <!--Requests Module-->
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-fw"></i>Requests Module &nbsp;&nbsp;<span class="fa arrow glyphicon glyphicon-send "></span></a>
                        <ul class="nav nav-second-level collapse">
                            <li>
                                <a href="/requests/permission/new">Permission</a>
                            </li>
                            <li>
                                <a href="/requests/vacation/new">Vacation</a>
                            </li>
                            <li>
                                <a href="/requests/workfromhome/new">Work From Home</a>
                            </li>
                            <li>
                                <a href="/requests/myrequests/index">My Requests</a>
                            </li>
                        </ul>
                    </li>

                    <li>
                        {{#visible}}
                        <a href="/sign/out"><i class="fa fa-bar-chart-o fa-fw"></i>Log out , Bye {{name}} &nbsp;&nbsp;<span class="fa arrow glyphicon glyphicon-log-out"></span></a>
                        {{/visible}} 
                    </li>
                </ul>
                
            </div>

            <div class="col-xs-9 col-md-9 content">
                <div>
                    {{$content}}{{/content}}  
                </div>
            </div>
        </div>
    </div>





    <script src="/bower_components/jquery/dist/jquery.min.js" type="text/javascript"></script>
    <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/bower_components/metisMenu/dist/metisMenu.min.js"></script>
    <script src="/bower_components/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js" type="text/javascript"></script>
    <script src="/js/confirmation.js" type="text/javascript"></script>

    <!-- Additional scripts to be added to specific views -->
    {{$scripts}}{{/scripts}}

</body>

</html>
