<!doctype html>
<html>

    <head>
        <title>Attendance System</title>
        <meta charset="UTF-8">

        <link rel="stylesheet" href="/css/template-styling.css" />
        <link href="/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
        <link href="/bower_components/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet" type="text/css"/>
        <link href="/bower_components/startbootstrap-sb-admin-2/dist/css/timeline.css" rel="stylesheet" type="text/css"/>
        <link href="/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <!-- Additional styles to be added to specific views -->
        {{$styles}}{{/styles}}

    </head>

    <body>

        <div id="wrapper">

            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/index">Attendance HUB</a>
                </div>
                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav in" id="side-menu">
                            <li>
                                <h3><i class="fa fa-dashboard fa-fw"></i> Dashboard</h3>
                            </li>
                            {{#visibleUserModule}}
                            <!--Users Module-->
                            <li>
                                <a href="/users">Users Module &nbsp;&nbsp;<i class="fa fa-user fa-fw"></i></a>
                            </li>
                            <!--Users Module-->
                            {{/visibleUserModule}}
                            <!--Settings Module-->
                            {{#visibleSettingsModule}}
                            <li>
                                <a href="#" >Settings Module&nbsp;&nbsp;<i class="glyphicon  glyphicon-wrench fa-fw " ></i><span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level collapse">
                                    <li>
                                        <a href="/settings/vacation/index">Vacation</a>
                                    </li>
                                    <li>
                                        <a href="/settings/holiday/index">Holidays</a>
                                    </li>
                                    <li>
                                        <a href="/settings/attendance/index">Attendance</a>
                                    </li>
                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <!--Settings Module-->
                            {{/visibleSettingsModule}}
                            <!--Requests Module-->
                            <li>
                                <a href="#">Requests Module &nbsp;&nbsp;<i class="glyphicon  glyphicon-send fa-fw " ></i><span class="fa  arrow  "></span></a>
                                <ul class="nav nav-second-level collapse">
                                    <li>
                                        <a href="/requests/myrequests/index">My Requests</a>
                                    </li>
                                    <li>
                                        <a href="/requests/permission/new">Permission</a>
                                    </li>
                                    <li>
                                        <a href="/requests/vacation/new">Vacation</a>
                                    </li>
                                    <li>
                                        <a href="/requests/workfromhome/new">Work From Home</a>
                                    </li>
                                </ul>
                            </li>
                            
                            <!--my attendance-->
                            <!--Requests Module-->
                            <li>
                                <a href="#">My Attendance Module &nbsp;&nbsp;<i class=" fa fa-file fa-fw " ></i><span class="fa  arrow  "></span></a>
                                <ul class="nav nav-second-level collapse">
                                    <li>
                                        <a href="/myattendance/attendance">My Attendance </a>
                                    </li>
                                    <li>
                                        <a href="/myattendance/vacation">My Vacations</a>
                                    </li>
                                    <li>
                                        <!--<a href="/requests/workfromhome/new">Work From Home</a>-->
                                    </li>
                                    <li>
                                        <!--<a href="/requests/myrequests/index">My Requests</a>-->
                                    </li>
                                </ul>
                            </li>
                            <!--my attendance--> 
                            
                            <li>
                                {{#visible}}
                                <a href="/calendar">Holiday Calendar &nbsp;&nbsp;<i class="fa fa-calendar fa-fw " ></i></a>
                                {{/visible}} 
                            </li>
                            <!--log out-->
                            <li>
                                {{#visible}}
                                <a href="/sign/out">Log out , Bye {{name}} &nbsp;&nbsp;<i class="glyphicon glyphicon-log-out fa-fw " ></i><span class="fa arrow glyphicon glyphicon-log-out"></span></a>
                                {{/visible}} 
                            </li>
                        </ul>
                    </div>
                    <!-- /.sidebar-collapse -->
                </div>
                <!-- /.navbar-static-side -->
            </nav>

            <div id="page-wrapper">

                <!-- /.row -->
                <div class="row">
                    <div class="col-lg-12">
                        {{$content}}{{/content}}  
                        <!-- /.panel-footer -->
                    </div>
                    <!-- /.panel .chat-panel -->
                </div>
                <!-- /.col-lg-4 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->









        <script src="/bower_components/jquery/dist/jquery.min.js" type="text/javascript"></script>
        <script src="/bower_components/bootstrap/dist/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="/bower_components/metisMenu/dist/metisMenu.min.js"></script>
        <script src="/bower_components/startbootstrap-sb-admin-2/dist/js/sb-admin-2.js" type="text/javascript"></script>
        <script src="/js/confirmation.js" type="text/javascript"></script>

        <!-- Additional scripts to be added to specific views -->
        {{$scripts}}{{/scripts}}

    </body>

</html>
